export { default as About } from "./About"
export { default as Home } from "./Home"
export { default as Cantact } from "./Contact"
export { default as AutoBoom } from "./AutoBoom"
export { default as Portfolio } from "./Portfolio"
export { default as News } from "./News"
